name: AndrewKincaid
favicon: null
layout_spectrum: 0.7691467746626586
typography_spectrum: 0.6709918742999434
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.21454113419167697
  lightness: 0.45046040415763855
  saturation: 0.21876929560676217
  rhythmicContrast: 0.6231783127877861
purpose: []
